# Generated by Django 5.2.17 on 2026-08-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='scans/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('detecting', 'Detecting spines'), ('reading', 'Reading spines'), ('matching', 'Matching to catalog'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('is_omnibus', models.BooleanField(default=False)),
                ('contained_titles', models.JSONField(blank=True, default=list)),
                ('norm_title', models.CharField(db_index=True, editable=False, max_length=500)),
                ('norm_author', models.CharField(db_index=True, editable=False, max_length=300)),
            ],
            options={
                'ordering': ('title', 'author'),
                'indexes': [models.Index(fields=['norm_title', 'norm_author'], name='scanner_cat_norm_ti_c17900_idx')],
                'constraints': [models.UniqueConstraint(fields=('norm_title', 'norm_author'), name='unique_catalog_title_author')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(default=list)),
                ('crop', models.FileField(blank=True, upload_to='crops/%Y/%m/')),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_title', models.CharField(blank=True, max_length=500)),
                ('raw_author', models.CharField(blank=True, max_length=300)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('margin', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_matched', 'Auto-matched'), ('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='scanner.catalogbook')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='scanner.scan')),
            ],
            options={
                'ordering': ('scan', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('scan', 'From a scan'), ('manual', 'Added by hand')], default='scan', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entries', to='scanner.catalogbook')),
                ('detection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_book', to='scanner.detection')),
            ],
            options={
                'ordering': ('-added_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('catalog_book__isnull', False)), fields=('catalog_book',), name='unique_library_catalog_book')],
            },
        ),
    ]
