# Generated by Django 5.2.17 on 2026-08-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=300)),
                ('is_omnibus', models.BooleanField(default=False)),
                ('contained_titles', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timings', models.JSONField(blank=True, default=dict)),
                ('used_full_image_fallback', models.BooleanField(default=False)),
                ('empty_result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('crop', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('read_title', models.CharField(blank=True, max_length=500, null=True)),
                ('read_author', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('auto_added', 'Auto-added'), ('needs_review', 'Needs review'), ('unmatched', 'Unmatched'), ('unreadable', 'Unreadable'), ('failed', 'Failed'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], default='unmatched', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scanner.catalogbook')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=500)),
                ('custom_author', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scanner.catalogbook')),
                ('source_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entries', to='scanner.detection')),
            ],
        ),
    ]
