# Generated by Django 5.2.17 on 2026-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='timings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
