# Generated by Django 5.2.17 on 2026-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogbook',
            name='spine_color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='catalogbook',
            name='spine_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
