# Generated by Django 5.2.17 on 2026-08-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_catalogbook_spine_color_catalogbook_spine_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='read_spine_color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
