# Generated by Django 5.2.17 on 2026-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
