# Generated by Django 5.2.17 on 2026-08-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scan_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='scanner.detection'),
        ),
    ]
